### ISSUE TITLE
keep getting errors

### ISSUE THREAD

**Issue by maique** [klaut/brio#6]
hi,

i'm way over my head on this, but would really like to try your app.
following the instructions i get to a dead end.

some comands (help, list) work, but can't get anything else to do the same.
i did get the 'SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed on error;' and tried to correct it the way you posted.

and i still can't get a simple stream request without an error.
i get '/usr/local/rvm/gems/ruby-1.9.3-p194/gems/highline-1.6.15/lib/highline/system_extensions.rb:184: warning: Insecure world writable dir /usr/local in PATH, mode 040777' every time, and i have no idea where to go from here.

i did get a 'Error running 'make ', please read /usr/local/rvm/log/openssl/make.log' when i first try to install 'rvm pkg install openssl ', so that might be causing some of this mess....

sorry about all this...

**Comment by klaut** [comment]
Hi @maique 

Sorry to hear you are stuck with this!

Let me understand this: do you just get the warning when you run brio or it does not work at all?

It seems to me that the permissions of the /usr/local directories got messed up. Try running Repair Permissions with Disk Utility and see if this fixes the warning.

**Comment by klaut** [comment]
Another thing that coudl fix this is that you uninstall rvm, and then try to reinstall it, but as a single user (so that it gets installed into your $HOME directory):
https://rvm.io/rvm/install/

**Comment by maique** [comment]
hi,

no worries, i just wanted to see if i could get it to work.

i get brio to work, i guess, because i can get 'brio help' to work.
most of the other commands just get the error i posted.

i tried repairing permissions (yesterday, for another issue with @kiwi) and
again today.
it changes nothing...

i'll try figuring out this last thing you suggested but, from looking at
the rvm site i can already tell that i'm wayyyy out of my league here.

again, thanks for your help, but don't worry. i just thought it would be
cool to use brio, but i'm not really a very CLI-oriented person... :-)

i'll keep you posted if i manage to get it to work eventually.

On Wed, Mar 6, 2013 at 11:03 AM, Tanja Pislar notifications@github.com
 wrote:

> Hi @maique https://github.com/maique
> 
> Sorry to hear you are stuck with this!
> 
> Let me understand this: do you just get the warning when you run brio or
> it does not work at all?
> 
> It seems to me that the permissions of the /usr/local directories got
> messed up. Try running Repair Permissions with Disk Utility and see if this
> fixes the warning.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/klaut/brio/issues/6#issuecomment-14493711
> .

**Comment by klaut** [comment]
Let my try and help:

( I am assuming you have rvm installed, but let me know if this is not the case )

Run: 

```
$ rvm info
```

And locate the PATH output and see where rvm is installed. From your error above, this would be "/usr/local/rvm". You will have to delete this folder (what is inside /usr/local/rvm) and reinstall rvm again but this time make sure it gets installed into your $HOME directory:

```
$ \curl -L https://get.rvm.io | bash -s stable
```

Then you need to install ruby:

```
$ rvm install 1.9.3
```

And if you want, you tell rvm to make ruby 1.9.3 your default one:

```
$ rvm --default use 1.9.3
```

and then you install brio again:

```
$ gem install brio
```

This also means that if you have installed other rubies and gems with rvm, they will need to be reinstalled again as well.

**Comment by maique** [comment]
followed the instructions. rvm was already installed.
it seemed to be somewhere else, but my PATH was wayyy longer than
'usr/local/rvm'...

anyway, did it twice, because something always keeps failing, and i ended
up much worse (in terms of errors) than before.

and again...

when i get to install brio it seems to work, 'help' works again.
but, 'stream' gets me

/Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/highline-1.6.15/lib/highline/system_extensions.rb:184:
warning: Insecure world writable dir /usr/local in PATH, mode 040777
error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate
B: certificate verify failed

again.
'whois' does the same.

stuck again.
sorry.

**Comment by klaut** [comment]
If repairing permissions with Disk Utility did not help (but do try it again) then try to fix the permissions manually:

```
$ sudo chmod go-w /usr/local
```

SSL error should be fixed with this:

```
$ rvm pkg install openssl  
$ rvm reinstall 1.9.3 --with-openssl-dir=$rvm_path/usr --skip-openssl
```

let me know how it goes.

**Comment by maique** [comment]
ok... repaired permissions, and did both of the lines on the SSL fix.

a call for help on brio now gets me this

```
Warning: no such file to load -- net/https. Make sure openssl is installed if you want ssl support
/Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday/adapter/net_http.rb:26:in         `<class:NetHttp>': cannot load such file -- openssl (LoadError)
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday/adapter/net_http.rb:11:in    `<class:Adapter>'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday/adapter/net_http.rb:10:in `<module:Faraday>'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday/adapter/net_http.rb:9:in `<top (required)>'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday.rb:67:in `const_get'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday.rb:67:in `lookup_middleware'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday/builder.rb:146:in `use_symbol'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday/builder.rb:108:in `adapter'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/brio-0.0.4/lib/brio/client.rb:25:in `block in initialize'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday/connection.rb:59:in `initialize'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday.rb:11:in `new'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/faraday-0.8.6/lib/faraday.rb:11:in `new'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/brio-0.0.4/lib/brio/client.rb:22:in `initialize'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/brio-0.0.4/bin/brio:13:in `new'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/gems/brio-0.0.4/bin/brio:13:in `<top (required)>'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/bin/brio:19:in `load'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/bin/brio:19:in `<main>'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
from /Users/maique/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
```

easy way out ? or should we just give up ? i don't want to take too much of your time, and you've been more than helpful already..

**Comment by klaut** [comment]
let's try this one more time :)

perhaps using --skip-openssl was not a good idea.

try running this again:

```
$ gem uninstall brio
$ rvm pkg install openssl  
$ rvm reinstall 1.9.3 --with-openssl-dir=$rvm_path/usr
$ gem install brio
```

**Comment by maique** [comment]
i get the same thing :-(

**Comment by klaut** [comment]
Are you getting the same error as in your last comment? "Warning: no such file to load -- net/https. Make sure openssl is installed..."

**Comment by maique** [comment]
same one.

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @aixiwang, @LJlkdskdjflsa, @ssetzer, @DancingWing, @itsMeNoName, @dnoursi, @MadBananaUnionDAO
